# Generated by Django 2.1.3 on 2019-04-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='maritalStatus',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
