# Generated by Django 2.1.3 on 2019-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0002_cast_maritalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='origin',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
