# Generated by Django 2.1.3 on 2019-04-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_cast_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='photo',
            field=models.ImageField(blank=True, upload_to='actors'),
        ),
    ]
