# Generated by Django 2.1.3 on 2019-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0005_cast_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='birthPlace',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
