# Generated by Django 2.1.3 on 2019-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0006_cast_birthplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='profession',
            field=models.ManyToManyField(to='cast.profession'),
        ),
    ]
