# Generated by Django 2.1.3 on 2019-04-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0007_auto_20190411_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='profession',
        ),
        migrations.DeleteModel(
            name='profession',
        ),
    ]
