# Generated by Django 2.1.3 on 2019-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0009_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='profession',
            field=models.ManyToManyField(to='cast.profession'),
        ),
    ]
