# Generated by Django 2.1.3 on 2019-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0010_cast_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=15)),
                ('dob', models.DateField()),
                ('birthPlace', models.CharField(max_length=1000)),
                ('biography', models.CharField(max_length=1000)),
                ('photo', models.ImageField(blank=True, upload_to='actors')),
                ('maritalStatus', models.CharField(max_length=120)),
                ('origin', models.CharField(max_length=100)),
                ('profession', models.ManyToManyField(to='cast.profession')),
            ],
        ),
        migrations.CreateModel(
            name='producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=15)),
                ('dob', models.DateField()),
                ('birthPlace', models.CharField(max_length=1000)),
                ('biography', models.CharField(max_length=1000)),
                ('photo', models.ImageField(blank=True, upload_to='actors')),
                ('maritalStatus', models.CharField(max_length=120)),
                ('origin', models.CharField(max_length=100)),
                ('profession', models.ManyToManyField(to='cast.profession')),
            ],
        ),
    ]
