# Generated by Django 2.1.7 on 2019-04-04 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GENRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('Review', models.CharField(max_length=1000)),
                ('reviewer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleName', models.CharField(max_length=120)),
                ('releaseDate', models.DateTimeField()),
                ('storyLine', models.CharField(max_length=1000)),
                ('budget', models.FloatField(null=True)),
                ('BoxOfficeCollection', models.FloatField(null=True)),
                ('titlePoster', models.ImageField(blank=True, null=True, upload_to='')),
                ('Review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.review')),
                ('actors', models.ManyToManyField(to='cast.cast')),
                ('genre', models.ManyToManyField(to='show.GENRE')),
                ('languages', models.ManyToManyField(to='show.language')),
            ],
        ),
    ]
