# Generated by Django 2.0.5 on 2019-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.AddField(
            model_name='show',
            name='genre',
            field=models.ManyToManyField(to='show.GENRE'),
        ),
    ]
