# Generated by Django 2.1.3 on 2019-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='suggested_count',
            field=models.IntegerField(default=0),
        ),
    ]
