# Generated by Django 2.1.7 on 2019-04-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='genre',
            new_name='GENRE',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='actors',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='languages',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Review',
            new_name='review',
        ),
    ]
