# Generated by Django 2.1.3 on 2019-04-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_review_date_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_reviewed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
