# Generated by Django 2.0.5 on 2019-03-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20190322_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='languages',
        ),
        migrations.AddField(
            model_name='show',
            name='languages',
            field=models.ManyToManyField(to='show.language'),
        ),
    ]
