# Generated by Django 2.1.7 on 2019-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20190404_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
