# Generated by Django 2.1.7 on 2019-04-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_auto_20190406_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='titlePoster',
            field=models.ImageField(blank=True, null=True, upload_to='titlePosters'),
        ),
    ]
