# Generated by Django 2.1.2 on 2019-04-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20190406_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='titlePoster',
            field=models.ImageField(blank=True, upload_to='movie_posters'),
        ),
    ]
