# Generated by Django 2.1.3 on 2019-04-22 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_auto_20190422_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 22, 16, 35, 59, 987549)),
        ),
    ]
