# Generated by Django 2.1.3 on 2019-04-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_auto_20190408_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='titlePoster1',
            field=models.ImageField(blank=True, upload_to='movie_posters'),
        ),
        migrations.AlterField(
            model_name='show',
            name='storyLine',
            field=models.CharField(max_length=2500),
        ),
    ]
