# Generated by Django 2.1.3 on 2019-04-22 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_auto_20190422_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_reviewed',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 22, 16, 55, 47, 907011)),
        ),
    ]
