# Generated by Django 2.1.3 on 2019-04-22 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0010_auto_20190422_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_reviewed',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
