# Generated by Django 2.2 on 2019-04-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_auto_20190408_1749'),
        ('show', '0011_auto_20190411_1258'),
        ('show', '0008_auto_20190407_1228'),
    ]

    operations = [
    ]
