# Generated by Django 2.1.3 on 2019-04-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_auto_20190407_1228'),
        ('show', '0011_auto_20190411_1258'),
        ('show', '0008_auto_20190408_1749'),
    ]

    operations = [
    ]
