# Generated by Django 2.1.3 on 2019-04-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0011_auto_20190422_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
