# Generated by Django 2.1.2 on 2019-04-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
    ]
